### ISSUE TITLE
Question: Is it possible to set "emit_schema_even_primitive_type" from command line?

### ISSUE THREAD

**Issue by krzosa** [podhmo/swagger-marshmallow-codegen#102]
Hello, I have a small problem in that some of the schemas I defined are being skipped. I looked through the source code and tested that this behaviour is configurable in that if I comment out this line of code I can get the result I want:
``` Python
# swagger-marshmallow-codegen/swagger_marshmallow_codegen/codegen/v2/codegen.py:432
if not self.config.get(
  "emit_schema_even_primitive_type", False
  ) and not self.resolver.has_schema(d, definition):
    logger.info("write schema: skip %s", schema_name)
    continue
```
So my question is how can I avoid altering the source. Is it possible to set the `emit_schema_even_primitive_type` from the command line? I couldn't find how to do it. Thanks in advance!

**Comment by podhmo** [comment]
Ah, It does not have this option as a command-line option, currently.

**Comment by podhmo** [comment]
Work-around: using `--driver` option, like this. https://github.com/podhmo/swagger-marshmallow-codegen/issues/1

**Comment by krzosa** [comment]
I had some problems with the --driver. How does it search for the classes? 
Let's say I'm doing:
```
--driver foo.driver:MyDriver
```
Does it search current_directory/foo/driver.py == class MyDriver? Or swagger-marshmallow-codegen/foo/driver.py? Cause I'm not sure how to hook it up.

Currently what I do is I create driver.py file with:
``` Python
from swagger_marshmallow_codegen.driver import Driver
class MyDriver(Driver):
    print("abc")
```
and from the same directory I invoke ```swagger-marshmallow-codegen --driver driver:MyDriver spec.yaml```

I get an error ```ModuleNotFoundError: No module named 'driver'```. I tried different approaches too and couldn't get it working.

**Comment by podhmo** [comment]
OK, sorry for rough communication, detail information is here.

the value `--driver` receiving is `<module>:<symbol name>` or `<file path>:<symbol name>`.

So, if your driver is just a python script file, use driver like here https://gist.github.com/podhmo/cc6fa27aa1bc0caaf8b8626f1676d1fe.
If your driver is defined in a module in some package, here https://gist.github.com/podhmo/621f84f88490dc49754ef9802356a5fc.
If

**Comment by podhmo** [comment]
> and from the same directory I invoke `swagger-marshmallow-codegen --driver driver:MyDriver spec.yaml`
> 
> I get an error `ModuleNotFoundError: No module named 'driver'`. I tried different approaches too and couldn't get it working.

So invoking`swagger-marshmallow-codegen --driver ./driver.py:MyDriver spec.yaml` or installing as a python package.

**Comment by krzosa** [comment]
Sorry for late response! I wrongfully assumed Github is going to notify me about the response in any way ;/. Thanks a lot for clarification! I will try this tomorrow. I will also write an update.

**Comment by krzosa** [comment]
I managed to get it working through setting up a package (your second example), thanks alot! I didn't got to editing the configs and drivers yet but so far it works.

I had some problems using the 'path to script method' (from first example). I'm posting the logs in case it would be helpful to you:

When I do a relative import I get:
```
swagger-marshmallow-codegen --driver ./mydriver:MyDriver swagger-spec.yaml 
```
```
Traceback (most recent call last):
  File "/home/sevni/.pyenv/versions/acapy1/bin/swagger-marshmallow-codegen", line 10, in <module>
    sys.exit(main())
  File "/home/sevni/.pyenv/versions/3.7.5/envs/acapy1/lib/python3.7/site-packages/swagger_marshmallow_codegen/cmd.py", line 58, in main
    driver = import_symbol(driver_cls, cwd=True)(config)
  File "/home/sevni/.pyenv/versions/3.7.5/envs/acapy1/lib/python3.7/site-packages/magicalimport/__init__.py", line 142, in import_symbol
    module = import_module(module_path, here=here, sep=sep, _depth=_depth, cwd=cwd)
  File "/home/sevni/.pyenv/versions/3.7.5/envs/acapy1/lib/python3.7/site-packages/magicalimport/__init__.py", line 130, in import_module
    return import_module_original(module_path)
  File "/home/sevni/.pyenv/versions/3.7.5/lib/python3.7/importlib/__init__.py", line 122, in import_module
    raise TypeError(msg.format(name))
TypeError: the 'package' argument is required to perform a relative import for './mydriver'
```
When I do absolute import I get:
```
could not import '/home/sevni/Documents/mydriver:MyDriver'
No module named '/home/sevni/Documents/mydriver'
Traceback (most recent call last):
  File "/home/sevni/.pyenv/versions/acapy1/bin/swagger-marshmallow-codegen", line 10, in <module>
    sys.exit(main())
  File "/home/sevni/.pyenv/versions/3.7.5/envs/acapy1/lib/python3.7/site-packages/swagger_marshmallow_codegen/cmd.py", line 58, in main
    driver = import_symbol(driver_cls, cwd=True)(config)
  File "/home/sevni/.pyenv/versions/3.7.5/envs/acapy1/lib/python3.7/site-packages/magicalimport/__init__.py", line 142, in import_symbol
    module = import_module(module_path, here=here, sep=sep, _depth=_depth, cwd=cwd)
  File "/home/sevni/.pyenv/versions/3.7.5/envs/acapy1/lib/python3.7/site-packages/magicalimport/__init__.py", line 130, in import_module
    return import_module_original(module_path)
  File "/home/sevni/.pyenv/versions/3.7.5/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named '/home/sevni/Documents/mydriver'
```

I will stick to the second method since it works for me. Thanks again for help.

**Comment by podhmo** [comment]
Hmm, this is a bug in another package, maybe. Thank you for sharing the information.

**Comment by podhmo** [comment]
Ah, use `./mydriver.py:MyDriver` instead of `./mydriver:MyDriver`.

> `swagger-marshmallow-codegen --driver ./mydriver:MyDriver swagger-spec.yaml `
