### ISSUE TITLE
snake_case attributes

### ISSUE THREAD

**Issue by Krolken** [podhmo/swagger-marshmallow-codegen#28]
Hello. 

Just tried the code generation and it seems to work very well. I am building an ORMish client to a web API using marshmallow as the serialiser and I would not want to type that much.

But I am interfacing to a .Net API which uses CamelCase. I want my code to be as "pythonic" as possible  so I am using snake_case attributes and then sets data_key to the actual field name.  I couldn't find a add this functionality by just skimming the code. 
If I would like to do this, where would be the point to add the function? There is no comments so it is a bit hard to get a grasp of the architecture.

**Comment by podhmo** [comment]
If you're expecting behaviour is like a below code.

```python
from schema import Person

d = {
    "name": "foo",
    "age": "20",
    "nickName": "F", # using camelCase
}

# `nickName` as `nick_name`.
print(Person().load(d))
# UnmarshalResult(data={'age': 20, 'name': 'foo', 'nick_name': 'F'}, errors={})
```

work-around is here.

1. Define custom Resolver with custom `resolve_normalized_name()` method
2. Define custom Driver using defined Resolver
3. using dfined Driver via `--driver` option

[gist is here](https://gist.github.com/podhmo/e57feb0073b0a76371226a2b0607552b)

(Sorry this is undocumented, and I'm not good at english, so, the motivation that writing documentation is low)

**Comment by podhmo** [comment]
:thought_balloon: if the feature you wanted is about [this feature](https://marshmallow.readthedocs.io/en/2.x-line/quickstart.html#specifying-attribute-names)

e.g. 

```python
from schema import Person
from collections import namedtuple

PersonModel = namedtuple("PersonModel", "name, age, nick_name")

d = {
    "name": "foo",
    "age": "20",
    "nickName": "F",
}

print(Person().dump(PersonModel(name="foo", age=20, nick_name="F")))
# MarshalResult(data={'name': 'foo', 'nickName': 'F', 'age': 20}, errors={})
```

hook point is not found. maybe...

**Comment by Krolken** [comment]
Cool. No problem with the docs. You answered fast.

I am after the first solution. The json with camelcase should be serialized into snake case class attributes.

But I think I found a larger issue. Today my code didn't work and i finnaly found that installing this lib downgraded to marshmallow 2.8 while I am using 3.x

Are your lib compatible with 3.x?

**Comment by podhmo** [comment]
sorry, 3.x is not supported, yet.

**Comment by podhmo** [comment]
#29

**Comment by Krolken** [comment]
OK. Then I'll at least try with the snake case driver so I don't have to write everything by hand.
Thanks.

**Comment by Krolken** [comment]
My solution

`
from swagger_marshmallow_codegen.langhelpers import normalize
from swagger_marshmallow_codegen.resolver import Resolver
import re

first_cap_re = re.compile('(.)([A-Z][a-z]+)')
all_cap_re = re.compile('([a-z0-9])([A-Z])')


def convert(name):
    s1 = first_cap_re.sub(r'\1_\2', name)
    return all_cap_re.sub(r'\1_\2', s1).lower()


class SnakeCaseResolver(Resolver):

    def resolve_normalized_name(self, name):
        norm = normalize(name)
        return convert(norm)


class SnakeCaseDriver(Driver):
    resolver_factory = SnakeCaseResolver
`
